#!/usr/bin/env bash
set -euo pipefail

MODE="symlink" # symlink|copy
PREFIX="${PREFIX:-$HOME/.local}"
BINDIR="${BINDIR:-}"
UNINSTALL=0
CONFIGURE_CODEX=0
CONFIGURE_CLAUDE=0
CONFIGURE_OPENCODE=0
CODEX_CONFIG_PATH="${CODEX_CONFIG_PATH:-}"
CLAUDE_CONFIG_PATH="${CLAUDE_CONFIG_PATH:-}"
OPENCODE_PLUGIN_PATH="${OPENCODE_PLUGIN_PATH:-}"

usage() {
    cat <<EOF
Usage: $0 [options]

Options:
  --prefix <dir>    Install prefix (default: \$HOME/.local)
  --bindir <dir>    Install directory for scripts (default: <prefix>/bin)
  --symlink         Install via symlinks (default)
  --copy            Install via copies
  --configure-codex Configure Codex notify hook (opt-in)
  --configure-claude Configure Claude hooks (opt-in)
  --configure-opencode Configure OpenCode plugin (opt-in)
  --codex-config <path>  Codex config.toml path (default: ~/.codex/config.toml)
  --claude-config <path> Claude settings.json path (default: ~/.claude/settings.json)
  --opencode-plugin-path <path> OpenCode plugins dir (default: ~/.config/opencode/plugins)
  --uninstall       Remove installed files
  -h, --help        Show help

Examples:
  $0 --prefix "\$HOME/.local" --symlink
  $0 --bindir "\$HOME/bin" --copy
  $0 --prefix "\$HOME/.local" --symlink --configure-codex
  $0 --prefix "\$HOME/.local" --symlink --configure-claude
  $0 --prefix "\$HOME/.local" --symlink --configure-opencode
EOF
}

die() {
    echo "Error: $*" >&2
    exit 1
}

timestamp() {
    date +"%Y%m%d%H%M%S" 2>/dev/null || date
}

backup_file() {
    local path="$1"
    [ -f "$path" ] || return 0
    local ts
    ts="$(timestamp)"
    cp -p "$path" "$path.bak.$ts"
}

ensure_parent_dir() {
    local path="$1"
    mkdir -p "$(dirname "$path")"
}

configure_codex() {
    local notify_cmd="$1"
    local cfg="${CODEX_CONFIG_PATH:-$HOME/.codex/config.toml}"

    ensure_parent_dir "$cfg"

    toml_root_has_notify_key() {
        local path="$1"
        awk '
            BEGIN { in_root = 1 }
            {
                line = $0
                sub(/^[ \t]+/, "", line)
                if (line ~ /^#/) next
                sub(/[ \t]*#.*/, "", line)
                if (line ~ /^\[\[?[^]]+\]\]?/) { in_root = 0 }
                if (in_root && line ~ /^notify[ \t]*=/) { found = 1; exit }
            }
            END { exit(found ? 0 : 1) }
        ' "$path" >/dev/null 2>&1
    }

    toml_root_has_string() {
        local path="$1"
        local needle="$2"
        awk -v needle="$needle" '
            BEGIN { in_root = 1 }
            {
                line = $0
                sub(/^[ \t]+/, "", line)
                if (line ~ /^#/) next
                sub(/[ \t]*#.*/, "", line)
                if (line ~ /^\[\[?[^]]+\]\]?/) { in_root = 0 }
                if (in_root && index(line, needle) > 0) { found = 1; exit }
            }
            END { exit(found ? 0 : 1) }
        ' "$path" >/dev/null 2>&1
    }

    toml_any_has_notify_key() {
        local path="$1"
        awk '
            {
                line = $0
                sub(/^[ \t]+/, "", line)
                if (line ~ /^#/) next
                sub(/[ \t]*#.*/, "", line)
                if (line ~ /^notify[ \t]*=/) { found = 1; exit }
            }
            END { exit(found ? 0 : 1) }
        ' "$path" >/dev/null 2>&1
    }

    insert_root_notify_block() {
        local path="$1"
        local cmd="$2"
        local tmp
        tmp="$(mktemp)"
        awk -v cmd="$cmd" '
            function print_block(at_top) {
                if (!at_top) print ""
                print "# Added by tmux-notify-jump install.sh"
                printf("notify = [\"%s\"]\n", cmd)
                print ""
            }
            BEGIN { inserted = 0 }
            {
                if (!inserted && $0 ~ /^[ \t]*\[\[?[^]]+\]\]?[ \t]*(#.*)?$/) {
                    print_block(NR == 1)
                    inserted = 1
                }
                print $0
            }
            END {
                if (!inserted) print_block(NR == 0)
            }
        ' "$path" >"$tmp"
        mv -f "$tmp" "$path"
    }

    if [ -f "$cfg" ]; then
        if toml_root_has_string "$cfg" "notify-codex.sh"; then
            echo "Codex already configured: $cfg"
            return 0
        fi
        if toml_root_has_notify_key "$cfg"; then
            echo "Codex config already has a top-level notify=; not modifying: $cfg"
            echo "Set it manually to include: $notify_cmd"
            return 0
        fi
        backup_file "$cfg"
        if toml_any_has_notify_key "$cfg"; then
            echo "Note: $cfg already contains notify= under a table; adding top-level notify= anyway."
        fi
        insert_root_notify_block "$cfg" "$notify_cmd"
        echo "Configured Codex notify hook in: $cfg"
        return 0
    fi

    backup_file "$cfg"
    {
        echo "# Codex config (generated by tmux-notify-jump install.sh)"
        printf 'notify = ["%s"]\n' "$notify_cmd"
    } >"$cfg"
    echo "Created Codex config with notify hook: $cfg"
}

configure_claude() {
    local notify_cmd="$1"
    local cfg="${CLAUDE_CONFIG_PATH:-$HOME/.claude/settings.json}"

    ensure_parent_dir "$cfg"

    if ! command -v python3 >/dev/null 2>&1; then
        echo "python3 not found; cannot auto-configure Claude settings. Edit manually:"
        echo "  ~/.claude/settings.json -> hooks Stop/Notification -> command: $notify_cmd"
        return 0
    fi

    if [ -f "$cfg" ]; then
        backup_file "$cfg"
    fi

    python3 - "$cfg" "$notify_cmd" <<'PY'
import json
import os
import sys

path = sys.argv[1]
cmd = sys.argv[2]

def load():
    if not os.path.exists(path):
        return {}
    with open(path, "r", encoding="utf-8") as f:
        s = f.read().strip()
        if not s:
            return {}
        return json.loads(s)

def ensure_obj(x):
    return x if isinstance(x, dict) else {}

def ensure_list(x):
    return x if isinstance(x, list) else []

data = ensure_obj(load())
hooks = data.setdefault("hooks", {})
if not isinstance(hooks, dict):
    # Don't clobber unknown schema
    print(f"Claude settings has non-object hooks; not modifying: {path}")
    sys.exit(0)

def has_command(event_name):
    ev = hooks.get(event_name)
    if not isinstance(ev, list):
        return False
    for entry in ev:
        if not isinstance(entry, dict):
            continue
        hook_list = entry.get("hooks")
        if not isinstance(hook_list, list):
            continue
        for h in hook_list:
            if not isinstance(h, dict):
                continue
            if h.get("type") != "command":
                continue
            existing = h.get("command")
            if existing == cmd:
                return True
    return False

if not has_command("Stop"):
    stop_list = hooks.get("Stop")
    if stop_list is None:
        hooks["Stop"] = []
        stop_list = hooks["Stop"]
    if not isinstance(stop_list, list):
        print(f"Claude hooks.Stop is not a list; not modifying: {path}")
        sys.exit(0)
    stop_list.append({"hooks": [{"type": "command", "command": cmd}]})

if not has_command("Notification"):
    notif_list = hooks.get("Notification")
    if notif_list is None:
        hooks["Notification"] = []
        notif_list = hooks["Notification"]
    if not isinstance(notif_list, list):
        print(f"Claude hooks.Notification is not a list; not modifying: {path}")
        sys.exit(0)
    notif_list.append(
        {
            "matcher": "permission_prompt|idle_prompt",
            "hooks": [{"type": "command", "command": cmd}],
        }
    )

with open(path, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
    f.write("\n")

print(f"Configured Claude hooks in: {path}")
PY
}

configure_opencode() {
    local plugin_dir="${OPENCODE_PLUGIN_PATH:-$HOME/.config/opencode/plugins}"
    local plugin_src="$REPO_DIR/opencode-plugin/tmux-notify-jump.ts"
    local plugin_dst="$plugin_dir/tmux-notify-jump.ts"

    if [ ! -f "$plugin_src" ]; then
        echo "Warning: plugin source not found: $plugin_src"
        return 0
    fi

    mkdir -p "$plugin_dir"

    if [ -f "$plugin_dst" ] || [ -L "$plugin_dst" ]; then
        local existing_target=""
        if [ -L "$plugin_dst" ]; then
            existing_target="$(readlink -f "$plugin_dst" 2>/dev/null || true)"
        fi
        if [ "$existing_target" = "$(readlink -f "$plugin_src" 2>/dev/null || true)" ]; then
            echo "OpenCode plugin already installed: $plugin_dst"
            return 0
        fi
        backup_file "$plugin_dst"
    fi

    case "$MODE" in
        symlink)
            ln -sf "$plugin_src" "$plugin_dst"
            ;;
        copy)
            cp -f "$plugin_src" "$plugin_dst"
            ;;
    esac

    echo "Installed OpenCode plugin: $plugin_dst"
    echo "Ensure notify-opencode.sh is on your PATH"
}

while [ $# -gt 0 ]; do
    case "$1" in
        --prefix)
            shift
            [ $# -gt 0 ] || die "--prefix requires a directory"
            PREFIX="$1"
            ;;
        --bindir)
            shift
            [ $# -gt 0 ] || die "--bindir requires a directory"
            BINDIR="$1"
            ;;
        --symlink)
            MODE="symlink"
            ;;
        --copy)
            MODE="copy"
            ;;
        --configure-codex)
            CONFIGURE_CODEX=1
            ;;
        --configure-claude)
            CONFIGURE_CLAUDE=1
            ;;
        --configure-opencode)
            CONFIGURE_OPENCODE=1
            ;;
        --codex-config)
            shift
            [ $# -gt 0 ] || die "--codex-config requires a path"
            CODEX_CONFIG_PATH="$1"
            ;;
        --claude-config)
            shift
            [ $# -gt 0 ] || die "--claude-config requires a path"
            CLAUDE_CONFIG_PATH="$1"
            ;;
        --opencode-plugin-path)
            shift
            [ $# -gt 0 ] || die "--opencode-plugin-path requires a path"
            OPENCODE_PLUGIN_PATH="$1"
            ;;
        --uninstall)
            UNINSTALL=1
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            die "Unknown option: $1"
            ;;
    esac
    shift
done

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ -z "$BINDIR" ]; then
    BINDIR="$PREFIX/bin"
fi

FILES=(
    tmux-notify-jump
    tmux-notify-jump-lib.sh
    tmux-notify-jump-linux.sh
    tmux-notify-jump-macos.sh
    tmux-notify-jump-hook.sh
    notify-codex.sh
    notify-claude-code.sh
    notify-opencode.sh
)

if [ "$UNINSTALL" -eq 1 ]; then
    for f in "${FILES[@]}"; do
        rm -f "$BINDIR/$f" 2>/dev/null || true
    done
    echo "Uninstalled from: $BINDIR"
    exit 0
fi

mkdir -p "$BINDIR"

for f in "${FILES[@]}"; do
    src="$REPO_DIR/$f"
    dst="$BINDIR/$f"
    [ -f "$src" ] || die "Missing source file: $src"

    chmod +x "$src" 2>/dev/null || true

    case "$MODE" in
        symlink)
            ln -sf "$src" "$dst"
            ;;
        copy)
            if command -v install >/dev/null 2>&1; then
                install -m 755 "$src" "$dst"
            else
                cp -f "$src" "$dst"
                chmod 755 "$dst"
            fi
            ;;
        *)
            die "Invalid MODE: $MODE"
            ;;
    esac
done

echo "Installed to: $BINDIR"
echo "Ensure it's on your PATH, e.g.: export PATH=\"$BINDIR:\$PATH\""

if [ "$CONFIGURE_CODEX" -eq 1 ]; then
    configure_codex "$BINDIR/notify-codex.sh"
fi

if [ "$CONFIGURE_CLAUDE" -eq 1 ]; then
    configure_claude "$BINDIR/notify-claude-code.sh"
fi

if [ "$CONFIGURE_OPENCODE" -eq 1 ]; then
    configure_opencode
fi
